name: CI

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:

#   rubocop:
#     name: Rubocop
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v1

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           bundler-cache: true  # runs 'bundle install' and caches installed gems automatically

#       - name: Analyze code
#         run: bundle exec rubocop

  rspec:
    name: RSpec
#     needs: rubocop
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:example@localhost:5432/db_test

    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true  # runs 'bundle install' and caches installed gems automatically

      - name: Install postgres dependecies
        run: sudo apt install libpq-dev

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0

      - name: Yarn package cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('./yarn.lock') }}

      - name: Create database
        run: bundle exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec --format progress


